services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.front
    restart: on-failure
    volumes:
      - "frontend_assets:/app/dist"
    env_file:
      - .env
    secrets:
      - ssl_key_front
      - ssl_crt_front
    ports:
      - "8080:443"
    networks:
      - web

# Include microservices from backend docker-compose
include:
  - ./backend/docker-compose.yml


volumes:
  frontend_assets:
  authDB:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend/auth/db'
  userDB:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend/user/db'
  jwtDB:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend/jwt/db'

networks:
  web:
    name: web
  backend:
    name: backend

secrets:
  ssl_key_front:
    file: "../.SECRET/private_key.key"
  ssl_crt_front:
    file: "../.SECRET/certificate.crt"
  ssl_key_back:
    file: "../.SECRET/private_key.pem"
  ssl_crt_back:
    file: "../.SECRET/certificate.pem"
