services:
  # backend:
  #   container_name: backend
  #   image: backend
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile.back
  #   env_file:
  #     - .env
  #   secrets:
  #     - ssl_key_back
  #     - ssl_crt_back
  #   ports:
  #     - "5000:3000"
  #   networks:
  #     - web
  #   volumes:
  #     - "database_assets:/app/dist/db"

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.front
    volumes:
      - "frontend_assets:/app/dist"
    env_file:
      - .env
    networks:
      - web

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: nginx
      dockerfile: Dockerfile.nginx
    depends_on:
      - frontend
    restart: on-failure
    volumes:
      - "frontend_assets:/usr/share/nginx/html"
    env_file:
      - .env
    secrets:
      - ssl_key_front
      - ssl_crt_front
    ports:
      - "8080:443"
    networks:
      - web

# Include microservices from backend docker-compose
include:
  - ./backend/docker-compose.yml


volumes:
  frontend_assets:
  userDB:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend/user/db'

networks:
  web:
    name: web
  backend:
    name: backend

secrets:
  ssl_key_front:
    file: "../.SECRET/private_key.key"
  ssl_crt_front:
    file: "../.SECRET/certificate.crt"
  ssl_key_back:
    file: "../.SECRET/private_key.pem"
  ssl_crt_back:
    file: "../.SECRET/certificate.pem"
